jdbc:
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: 123456
  url: jdbc:mysql://localhost:3306/demo?useUnicode=true&CharacterEncoding=utf8&useSSL=false
server:
  port: 8088
  context-path: /wechat

#Mybatis 的SQLSessionFactory设置
sqlSession:
  mybatisConfigFilePath: mybatis-config.xml
  mapperPath: /mapper/**.xml
  entityPackage: com.ghostben.wechat.demo.wechat.entity